// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProjektSemestralny.Logika.Data;

namespace ProjektSemestralny.Logika.Migrations
{
    [DbContext(typeof(ApplicationDBContext))]
    [Migration("20220531190308_new_products")]
    partial class new_products
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.15")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ProjektSemestralny.Logika.Data.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 10,
                            Name = "Mobiles"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Laptops"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Monitors"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Smartwatches"
                        },
                        new
                        {
                            Id = 14,
                            Name = "Soundbars"
                        },
                        new
                        {
                            Id = 15,
                            Name = "Projectors"
                        },
                        new
                        {
                            Id = 16,
                            Name = "Powerbanks"
                        },
                        new
                        {
                            Id = 17,
                            Name = "Printers"
                        },
                        new
                        {
                            Id = 18,
                            Name = "Consoles"
                        },
                        new
                        {
                            Id = 19,
                            Name = "Refrigerators"
                        },
                        new
                        {
                            Id = 20,
                            Name = "Washing machines"
                        },
                        new
                        {
                            Id = 21,
                            Name = "Ovens"
                        });
                });

            modelBuilder.Entity("ProjektSemestralny.Logika.Data.Models.CategoryProducent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<int>("ProducentId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("ProducentId");

                    b.ToTable("CategoryProducents");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 10,
                            ProducentId = 50
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 11,
                            ProducentId = 51
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 12,
                            ProducentId = 52
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 13,
                            ProducentId = 50
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 14,
                            ProducentId = 57
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 15,
                            ProducentId = 59
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 16,
                            ProducentId = 58
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 17,
                            ProducentId = 59
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 18,
                            ProducentId = 54
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 19,
                            ProducentId = 50
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 20,
                            ProducentId = 53
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 21,
                            ProducentId = 53
                        });
                });

            modelBuilder.Entity("ProjektSemestralny.Logika.Data.Models.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CategoryProducentId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("CategoryProducentId");

                    b.ToTable("Items");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryProducentId = 1,
                            Description = "Samsung's fastest, most powerful chip ever. That means, a faster CPU and GPU compared to Galaxy S21 Ultra. It’s an epic leap for smartphone technology.",
                            Name = "Galaxy S22 Ultra",
                            Price = 1199.0
                        },
                        new
                        {
                            Id = 2,
                            CategoryProducentId = 2,
                            Description = "Laptop dock for the Motorola ATRIX 4G for a more interactive computer-like experience from your smartphone",
                            Name = "ATRIX 4G",
                            Price = 500.0
                        },
                        new
                        {
                            Id = 3,
                            CategoryProducentId = 3,
                            Description = "6 Models of Entry-level Displays with 4K High-Definition Image Quality.",
                            Name = "TH-75CQ2U 75 4K UHD Professional TV",
                            Price = 600.0
                        },
                        new
                        {
                            Id = 4,
                            CategoryProducentId = 4,
                            Description = "Galaxy Watch4 Classic runs faster (compared to Galaxy Watch3), efficiently activates applications that you have even more space to do.",
                            Name = "Smartwatch SAMSUNG Galaxy Watch 4",
                            Price = 1199.0
                        },
                        new
                        {
                            Id = 5,
                            CategoryProducentId = 5,
                            Description = "Bose Voice4Video's unique technology extends voice control through Alex's assistant, something no other soundbar can do.",
                            Name = "Soundbar BOSE Smart Soundbar 900",
                            Price = 4699.0
                        },
                        new
                        {
                            Id = 6,
                            CategoryProducentId = 6,
                            Description = "Enjoy your favorite movies with this Full HD projector.",
                            Name = "Projektor EPSON EH-TW740",
                            Price = 2699.0
                        },
                        new
                        {
                            Id = 7,
                            CategoryProducentId = 7,
                            Description = "With a high capacity battery, you don't have to worry about running out of battery power on your device.",
                            Name = "Powerbank SBS 20000mAh Czarny TTBB20000FASTK",
                            Price = 119.0
                        },
                        new
                        {
                            Id = 8,
                            CategoryProducentId = 8,
                            Description = "Save up to 90% on printing costs with this Epson EcoTank L3251 printer.",
                            Name = "EPSON EcoTank L3251",
                            Price = 869.0
                        },
                        new
                        {
                            Id = 9,
                            CategoryProducentId = 9,
                            Description = "The PS5 takes gaming to a new level you don't even expect.",
                            Name = "PlayStation 5 B Chassis",
                            Price = 2799.0
                        },
                        new
                        {
                            Id = 10,
                            CategoryProducentId = 10,
                            Description = "The PS5 takes gaming to a new level you don't even expect.",
                            Name = "PlayStation 5 B Chassis",
                            Price = 2799.0
                        },
                        new
                        {
                            Id = 11,
                            CategoryProducentId = 11,
                            Description = "Looking for a unique refrigerator that fits perfectly into your kitchen style? If you're looking at design, the BESPOKE range of refrigerators will allow you to choose from a range of colors and textures.",
                            Name = "SAMSUNG Bespoke RB38A6B2E22/EF",
                            Price = 2949.0
                        },
                        new
                        {
                            Id = 12,
                            CategoryProducentId = 12,
                            Description = "The combination of steam and hot air ensures that the dishes do not dry and can be cooked at a lower temperature.",
                            Name = "ELECTROLUX EOC8H31Z",
                            Price = 2799.0
                        });
                });

            modelBuilder.Entity("ProjektSemestralny.Logika.Data.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Paid")
                        .HasColumnType("bit");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("ProjektSemestralny.Logika.Data.Models.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("OrderId")
                        .HasColumnType("int");

                    b.Property<int?>("ProductId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("ProjektSemestralny.Logika.Data.Models.Producent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Producents");

                    b.HasData(
                        new
                        {
                            Id = 50,
                            Name = "Samsung"
                        },
                        new
                        {
                            Id = 51,
                            Name = "Motorola"
                        },
                        new
                        {
                            Id = 52,
                            Name = "Panasonic"
                        },
                        new
                        {
                            Id = 53,
                            Name = "Electrolux"
                        },
                        new
                        {
                            Id = 54,
                            Name = "Sony"
                        },
                        new
                        {
                            Id = 55,
                            Name = "HP"
                        },
                        new
                        {
                            Id = 56,
                            Name = "Huawei"
                        },
                        new
                        {
                            Id = 57,
                            Name = "Boose"
                        },
                        new
                        {
                            Id = 58,
                            Name = "Sbs"
                        },
                        new
                        {
                            Id = 59,
                            Name = "Epson"
                        });
                });

            modelBuilder.Entity("ProjektSemestralny.Logika.Data.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Login")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("PasswordHash")
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("PasswordSalt")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Surname")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("ProjektSemestralny.Logika.Data.Models.CategoryProducent", b =>
                {
                    b.HasOne("ProjektSemestralny.Logika.Data.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProjektSemestralny.Logika.Data.Models.Producent", "Producent")
                        .WithMany()
                        .HasForeignKey("ProducentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Producent");
                });

            modelBuilder.Entity("ProjektSemestralny.Logika.Data.Models.Item", b =>
                {
                    b.HasOne("ProjektSemestralny.Logika.Data.Models.CategoryProducent", "CategoryProducent")
                        .WithMany()
                        .HasForeignKey("CategoryProducentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CategoryProducent");
                });

            modelBuilder.Entity("ProjektSemestralny.Logika.Data.Models.Order", b =>
                {
                    b.HasOne("ProjektSemestralny.Logika.Data.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ProjektSemestralny.Logika.Data.Models.OrderItem", b =>
                {
                    b.HasOne("ProjektSemestralny.Logika.Data.Models.Order", "Order")
                        .WithMany("Items")
                        .HasForeignKey("OrderId");

                    b.HasOne("ProjektSemestralny.Logika.Data.Models.Item", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId");

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("ProjektSemestralny.Logika.Data.Models.Order", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
